// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoTLrvB-EcUe9AtrsVmZYnqydMVHTvyQo',
    appId: '1:578322082537:web:7c45bee7ccc551d5c95e78',
    messagingSenderId: '578322082537',
    projectId: 'vetsys-aeeb6',
    authDomain: 'vetsys-aeeb6.firebaseapp.com',
    storageBucket: 'vetsys-aeeb6.appspot.com',
    measurementId: 'G-T0GHNDYLD4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaIjLp-PSWhaCxoay6s16qSVByxApD6n4',
    appId: '1:578322082537:android:a41ee3eb9240e90ac95e78',
    messagingSenderId: '578322082537',
    projectId: 'vetsys-aeeb6',
    storageBucket: 'vetsys-aeeb6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-_uXcRYpS3AW37_gNHOLlRygWO6nPxzE',
    appId: '1:578322082537:ios:a50668cfdd9ac30ec95e78',
    messagingSenderId: '578322082537',
    projectId: 'vetsys-aeeb6',
    storageBucket: 'vetsys-aeeb6.appspot.com',
    iosBundleId: 'com.example.rutasmicros',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-_uXcRYpS3AW37_gNHOLlRygWO6nPxzE',
    appId: '1:578322082537:ios:fa87e156ae62c779c95e78',
    messagingSenderId: '578322082537',
    projectId: 'vetsys-aeeb6',
    storageBucket: 'vetsys-aeeb6.appspot.com',
    iosBundleId: 'com.example.rutasmicros.RunnerTests',
  );
}
